### ISSUE TITLE
New release with new name?

### ISSUE THREAD

**Issue by legoktm** [php-parallel-lint/PHP-Console-Highlighter#1]
Can you tag a new release that uses the packages from the `php-parallel-lint` organization/vendor? Thanks!

**Comment by jrfnl** [comment]
Yes please!

Currently, if someone installs `php-console-highlighter`, they currently get the below warning as no release has been tagged with the updated dependency names:
`Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.`

**Comment by Judapriest** [comment]
Last release from @JakubOnderka v 0.4 date from 2018. Seems a bit outdated.

Maybe @grogy or @tomasfejfar, could you please release a new minor version from master ?

**Comment by jrfnl** [comment]
@Judapriest for "stable release", it would need to be a `1.0` version or higher...

**Comment by grogy** [comment]
For faster creation new version can you add changelog like https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/CHANGELOG.md as PR ? :-)

**Comment by Judapriest** [comment]
> @Judapriest for "stable release", it would need to be a `1.0` version or higher...

To be considered stable by composer, a release don't need the "major" digit to be superior to 1 ;)
i.e. 
- 0.4.0 is a stable release.
- dev-master is not considered a stable release by composer

@see https://packagist.org/packages/php-parallel-lint/php-console-highlighter

@reedy thx you for the PR.

Cheers guys !

**Comment by reedy** [comment]
> For faster creation new version can you add changelog like https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/CHANGELOG.md as PR ? :-)

And 13 days later... It's not been merged anyway...

**Comment by duxthefux** [comment]
does really no one of the contributors have time to look at this? 😢

**Comment by grogy** [comment]
Released new version - https://github.com/php-parallel-lint/PHP-Console-Highlighter/releases/tag/v0.5
