### ISSUE TITLE
Rename the namespace

### ISSUE THREAD

**Issue by jrfnl** [php-parallel-lint/PHP-Console-Highlighter#4]
The files currently still use the `JakubOnderka` top-level namespace. To prevent issues, it would probably be a good idea to switch this over to using `PHP_Parallel_Lint` or `PHPParallelLint`.

**Comment by peter279k** [comment]
I think this issue will be broken change.

Once this issue is accepted by repository owner, I think it should release `^1.x` version.

And it also create [branch-alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias) setting block on `composer.json`.
